### ISSUE TITLE
Can't seem to join paths . . .

### ISSUE THREAD

**Issue by fugueink** [Shriinivas/inkscapejoinpaths#1]
I may be using this wrong. I am not a very skilled user. I'm running Inkscape Inkscape 0.92.2 5c3e80d, 2017-08-06, which is the most recent build for macOS. (I'm running macOS 10.13.6, with the latest security update, which is the most advanced system my hardware allows.) I'm running XQuartz 2.7.11 (xorg-server 1.18.4) (the highest one of my apps allows).

I am trying to join one endpoint of a path to the endpoint of a different path. I tried the regular "Join paths" and got a weird thing that connected distant endpoints into a closed shape. (I'm looking to turn two lines into one line as a result.)

When I tried the optimized version, it failed (I think) and said:

>  Traceback (most recent call last):
>   File "join_paths_optim.py", line 155, in <module>
>     effect.affect()
>   File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex.py", line 283, in affect
>     self.effect()
>   File "join_paths_optim.py", line 120, in effect
>     pathIds = getArrangedIds(paths, startPathId)
>   File "join_paths_optim.py", line 73, in getArrangedIds
>     np = pathMap[nextPathId]
> KeyError: 'path846_joined'

I have no idea what all that means, but the paths do not behave as if they are joined. The two nodes I'm trying to get together still behave as separate.

My apologies if I am missing something obvious. Thank you for any assistance you can give me!

**Comment by fugueink** [comment]
By the way, I did see the video saying that I can just "correct" the odd segments. That's not working. Two distant points are connected directly, and I cannot get the line to curve in a way that disguises its prescence.

![FreakyJoin](https://user-images.githubusercontent.com/1401986/56171554-bb706200-5fb3-11e9-9529-71c532b80715.png)

The straight line is the one I want to make disappear, and the node between the two points is not on that line. Trying to delete the connection is not working.  Yes, I suppose I could add a node there on the straight line, but it seems a bit much tweaking. And shouldn't the optimized version generate something other than the error message?

Thank you!

**Comment by Shriinivas** [comment]
Sorry for the late reply (I am not getting notifications on the Github issues).

Are you still facing the problem? If yes, is it possible for you to share the svg file with both the actual and expected behaviour.
You can directly mail me at khemadeva@gmail.com

**Comment by Shriinivas** [comment]
Please reopen if you still face the issue.
